version: '3.7'
services:
  flask:
    build: .
    container_name: backend-flask
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - .:/backend
    ports:
      - "5000:5000"
    command: python report.py
