Return drivers list
Use order field to order by in [asc, desc] and format [json, xml]
---
parameters:
  - in: query
    name: order
    type: string
    enum: ['asc', 'desc']
  - in: query
    name: format
    type: string
    enum: ['json', 'xml']
responses:
  200:
    description: Race results
    schema:
      id: RaceReport
      properties:
        order:
          type: string
          description: Order by in [asc, desc] and format [json, xml]
          default: none